---
- name: Install OpenShift GitOps Operator
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', './templates/operator.yaml.j2') }}"

- name: Wait for OpenShift  GitOps Operator
  ansible.builtin.pause:
    seconds: 60

- name: Install OpenShift Gitops
  kubernetes.core.k8s:
    definition: |
      {{ lookup('kubernetes.core.kustomize',
      dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/openshift-gitops') }}
    state: present
  register: openshift_gitops_result
  ignore_errors: true

- name: Set argocd permissions for user {{ item }}
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/argocd-app-project.yaml.j2') | from_yaml }}"
  vars:
    namespace: "openshift-gitops"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Delete OpenShift Gitops
  kubernetes.core.k8s:
    definition: |
      {{ lookup('kubernetes.core.kustomize',
      dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/openshift-gitops') }}
    state: present
  register: openshift_gitops_result
  ignore_errors: true

- name: Create OpenShift Gitops
  kubernetes.core.k8s:
    definition: |
      {{ lookup('kubernetes.core.kustomize',
      dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/openshift-gitops') }}
    state: present
  register: openshift_gitops_result
  ignore_errors: true 

- name: Install Gitea
  ansible.builtin.include_role:
    name: ocp4_workload_gitea_operator

- name: Install OpenShift Pipelines
  kubernetes.core.k8s:
    definition: |
      {{ lookup('kubernetes.core.kustomize',
      dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/openshift-pipelines-operator/overlays/latest') }}
    state: present
  register: openshift_pipelines_result
  ignore_errors: false

- name: Wait for tkn-cli-serve pod to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: openshift-pipelines
    label_selectors:
      - app=tkn-cli-serve
  register: tkn_pod_info
  until: |
    tkn_pod_info.resources[0].status.phase == "Running"
    and tkn_pod_info.resources[0].status.conditions | selectattr("type", "equalto", "Ready")
    | map(attribute="status") | first == "True"
  retries: 30
  delay: 10
  ignore_errors: true

- name: Install and Deploy Quay
  ansible.builtin.include_tasks: quay-deployment.yml

- name: Register gitea route
  kubernetes.core.k8s_info:
    kind: Route
    namespace: gitea
    label_selectors:
      - app=gitea
  register: r_gitea
  until: r_gitea.resources[0].status.ingress[0].host is defined
  retries: 30
  delay: 10

- name: Debug gitea route
  ansible.builtin.debug:
    msg: "giteaRoute: {{ r_gitea.resources[0].status.ingress[0].host }}"
  failed_when: r_gitea.resources[0].status.ingress[0].host is not defined

- name: Set gitea route
  ansible.builtin.set_fact:
    ocp4_workload_argocd_quay_todo_app_gitea_route: "{{ r_gitea.resources[0].status.ingress[0].host }}"

- name: Set gitea repo url
  ansible.builtin.set_fact:
    ocp4_workload_argocd_quay_todo_app_gitea_repo_url: "{{ ocp4_workload_argocd_quay_todo_app_gitea_route }}/{{ ocp4_workload_gitea_user }}/todo-demo-app-helmrepo.git"

- name: Install Gitops Repo Secret
  kubernetes.core.k8s:
    state: present
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', './templates/gitops-repo-secret.yml.j2') }}"

- name: Add ArgoCD Task
  kubernetes.core.k8s:
    state: present
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', './templates/cluster-config.yaml.j2') }}"

- name: Create todo-demo-app namespace for user {{ item }}
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/todo-demo-app-namespace.yaml.j2') | from_yaml }}"
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Grant admin rights to user {{ item }} for namespace {{ namespace }}
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: admin-role-binding
        namespace: "{{ namespace }}"
      subjects:
      - kind: User
        name: "{{ user }}"
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: admin
        apiGroup: rbac.authorization.k8s.io
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Create group {{ item }}-group
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: "{{ user }}-group"
  vars:
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Add user {{ item }} to group {{ item }}-group
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: "{{ user }}-group"
      users:
        - "{{ user }}"
  vars:
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Add Git Commit Task to todo-demo-app namespace for user {{ item }}
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/git-commit.yaml.j2') | from_yaml }}"
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}" 
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Add Image pipeline resource to todo-demo-app namespace for user {{ item }}
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: image.openshift.io/v1
      kind: ImageStream
      metadata:
        name: "todo-demo-app-{{ item }}-image"
        namespace: "{{ namespace }}"
      spec:
        tags:
        - name: "latest"
          images:
          - namespace: "{{ namespace }}"
            name: "todo-demo-app"
            dockerImageRepository: "quay.io/{{ item }}/{{ item }}-image"
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Create PVC for todo-demo-app for user {{ item }}
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/pvc.yml.j2') | from_yaml }}"
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: push-todo-demo-app-image-to-quay Task
  kubernetes.core.k8s:
    state: present
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', 'templates/push-image-to-quay.yaml.j2') }}"
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: update-image-tag-in-git Task
  kubernetes.core.k8s:
    state: present
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', 'templates/update-image-tag-in-git.yaml.j2') }}"
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: maven-source-pvc Task
  kubernetes.core.k8s:
    state: present
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', 'templates/maven-source-pvc.yaml.j2') }}"
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: helm-repo-pvc Task
  kubernetes.core.k8s:
    state: present
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', 'templates/helm-repo-pvc.yaml.j2') }}"
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Save argocd-deploy-pipeline template output to file
  ansible.builtin.copy:
    content: "{{ lookup('template', 'templates/argocd-deploy-pipeline.yaml.j2') }}"
    dest: "/tmp/argocd-deploy-pipeline-{{ item }}.yaml"
  ignore_errors: false
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Debug saved argocd-deploy-pipeline file content for user {{ item }}
  ansible.builtin.command:
    cmd: cat /tmp/argocd-deploy-pipeline-{{ item }}.yaml
  register: debug_output
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Add Pipeline Task
  kubernetes.core.k8s:
    state: present
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', 'templates/argocd-deploy-pipeline.yaml.j2') }}"
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item


    loop_var: item

- name: Patch Service Account in todo-demo-app namespace for user with container secret {{ item }}
  kubernetes.core.k8s:
    state: patched
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', 'templates/service-account.yaml.j2') | from_yaml }}"
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Add Pipeline Task Service Account Permissions
  kubernetes.core.k8s:
    state: present
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', 'templates/pipeline-sa-permissions.yaml.j2') }}"
  vars:
    namespace: "todo-demo-app-{{ item }}"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Set gitea namespace permissions for user {{ item }}
  kubernetes.core.k8s:
    state: present
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', 'templates/view-role-binding.yaml.j2') }}"
  vars:
    namespace: "gitea"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Set openshift-gitops namespace permissions for user {{ item }}
  kubernetes.core.k8s:
    state: present
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', 'templates/view-role-binding.yaml.j2') }}"
  vars:
    namespace: "openshift-gitops"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

- name: Set quay-registry namespace permissions for user {{ item }}
  kubernetes.core.k8s:
    state: present
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', 'templates/view-role-binding.yaml.j2') }}"
  vars:
    namespace: "quay-registry"
    user: "{{ item }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: item

# Leave this as the last task in the playbook.
- name: Workload tasks complete
  ansible.builtin.debug:
    msg: "Workload Tasks completed successfully."
  when: not silent
